* gp + colocation logs
W0721 04:22:38.322993 40623 multi_step_monitored_task.cc:214] TableSchemaVerificationTask for l_rd [id=00004100000030008000000000004080][0x000071993db15520]: Task failed: Aborted (yb/master/ysql_ddl_verification_task.cc:268): Not performing transaction verification for table l_rd [id=00004100000030008000000000004080] as it no longer has any transaction verification state
W0721 04:22:38.323073 40623 multi_step_monitored_task.cc:157] Failed task TableSchemaVerificationTask for l_rd [id=00004100000030008000000000004080][0x000071993db15520]: : Aborted (yb/master/ysql_ddl_verification_task.cc:268): Not performing transaction verification for table l_rd [id=00004100000030008000000000004080] as it no longer has any transaction verification state
W0721 04:30:56.517409  8575 catalog_manager.cc:8156] Unable to find schema name for YSQL table yb1.l_pk_sk due to error: Not found (yb/master/ysql/ysql_manager.cc:264): No committed pgsql table was found for DocDB table : 00004100000030008000000000004084: DOCDB_TABLE_NOT_COMMITTED (master error 43)
W0721 04:30:56.517477  8575 catalog_manager.cc:8156] Unable to find schema name for YSQL table yb1.lineitem_1a_l_partkey_l_suppkey_idx due to error: Not found (yb/master/ysql/ysql_manager.cc:264): No committed pgsql table was found for DocDB table : 00004100000030008000000000004085: DOCDB_TABLE_NOT_COMMITTED (master error 43)
W0721 04:36:55.970633 49739 multi_step_monitored_task.cc:214] TableSchemaVerificationTask for l_pk_sk [id=00004100000030008000000000004084][0x00007199338818a0]: Task failed: Aborted (yb/master/ysql_ddl_verification_task.cc:268): Not performing transaction verification for table l_pk_sk [id=00004100000030008000000000004084] as it no longer has any transaction verification state
W0721 04:36:55.970700 49739 multi_step_monitored_task.cc:157] Failed task TableSchemaVerificationTask for l_pk_sk [id=00004100000030008000000000004084][0x00007199338818a0]: : Aborted (yb/master/ysql_ddl_verification_task.cc:268): Not performing transaction verification for table l_pk_sk [id=00004100000030008000000000004084] as it no longer has any transaction verification state


W0721 04:25:04.469636 39371 column_family.cc:609] T a3bc7e0530cf452cb64614a4944b0749 P a3a39729c5404f3486e45a5160a7d655 [I]: [default] Stopping writes because we have 318270957 bytes to flush, while 262144000 is allowed



Found 5 errors:
Table partsupp with oid 16405 and uuid 00004100000030008000000000004015 exists in yb1 but master leader API returns wrong table details - {"table_name":"yb1.partsupp","table_id":"00004100000030008000000000004015","table_version":18,"table_type":"PGSQL_TABLE_TYPE","table_state":"Running","table_state_message":"Current schema version=18","table_replication_info":{"live_replicas":{"num_replicas":3,"placement_blocks":[{"cloud_info":{"placement_cloud":"aws","placement_region":"us-west-2","placement_zone":"us-west-2a"},"min_num_replicas":1},{"cloud_info":{"placement_cloud":"aws","placement_region":"us-west-2","placement_zone":"us-west-2b"},"min_num_replicas":1},{"cloud_info":{"placement_cloud":"aws","placement_region":"us-west-2","placement_zone":"us-west-2c"},"min_num_replicas":1}],"placement_uuid":"d49113b5-a059-4778-9a13-f51b9b70beb9"},"affinitized_leaders":[{"placement_cloud":"aws","placement_region":"us-west-2","placement_zone":"us-west-2a"},{"placement_cloud":"aws","placement_region":"us-west-2","placement_zone":"us-west-2b"},{"placement_cloud":"aws","placement_region":"us-west-2","placement_zone":"us-west-2c"}]},"table_transaction_verifier_state":"cccd9547-f6df-4e41-9fd3-083dc30b1e4d","table_transaction_ddl":" Alter ","table_transaction_ddl_previous_table_name":"partsupp","table_transaction_ddl_previous_table_previous_schema":{"columns":[{"id":0,"name":"ps_partkey","type":{"main":"INT32"},"is_key":true,"is_nullable":false,"is_static":false,"is_counter":false,"sorting_type":2,"order":1,"pg_type_oid":23,"marked_for_deletion":false},{"id":1,"name":"ps_suppkey","type":{"main":"INT32"},"is_key":true,"is_nullable":false,"is_static":false,"is_counter":false,"sorting_type":2,"order":2,"pg_type_oid":23,"marked_for_deletion":false},{"id":2,"name":"ps_availqty","type":{"main":"INT32"},"is_key":false,"is_nullable":true,"is_static":false,"is_counter":false,"sorting_type":0,"order":3,"pg_type_oid":23,"marked_for_deletion":false},{"id":3,"name":"ps_supplycost","type":{"main":"DECIMAL"},"is_key":false,"is_nullable":true,"is_static":false,"is_counter":false,"sorting_type":0,"order":4,"pg_type_oid":1700,"marked_for_deletion":false},{"id":4,"name":"ps_comment","type":{"main":"STRING"},"is_key":false,"is_nullable":true,"is_static":false,"is_counter":false,"sorting_type":0,"order":5,"pg_type_oid":1043,"marked_for_deletion":false}],"table_properties":{"contain_counters":false,"is_transactional":true,"consistency_level":"STRONG","use_mangled_column_name":false,"is_ysql_catalog_table":false,"retain_delete_markers":false,"partitioning_version":1,"ysql_replica_identity":"CHANGE"},"colocated_table_id":{"colocation_id":3707291260},"DEPRECATED_pgschema_name":"public"},"table_transaction_ddl_previous_table_current_schema":"columns",[{"column":"ps_partkey","id":"0","type":"int32 NOT NULL RANGE_DESC_NULL_FIRST"},{"column":"ps_suppkey","id":"1","type":"int32 NOT NULL RANGE_DESC_NULL_FIRST"},{"column":"ps_availqty","id":"2","type":"int32 NULLABLE VALUE"},{"column":"ps_supplycost","id":"3","type":"decimal NULLABLE VALUE"},{"column":"ps_comment","id":"4","type":"string NULLABLE VALUE"}]:"tablets",[{"tablet_id":"a0af6e0c05d54f42a3580b9b9b255fc3","partition":"range: [&lt;start&gt;, &lt;end&gt;)","split_depth":0,"state":"Running","hidden":"false","message":"Tablet reported with an active leader","locations":[{"uuid":"6a397d935f694cd6aeb4e3b9c530ab72","role":"FOLLOWER","location":"http://172.151.28.142:9000/tablet?id=a0af6e0c05d54f42a3580b9b9b255fc3"},{"uuid":"a1f057437c314e669b73c41e9e326a59","role":"LEADER","location":"http://172.151.37.176:9000/tablet?id=a0af6e0c05d54f42a3580b9b9b255fc3"},{"uuid":"b15bbdee27b7436aa117cc780169e62f","role":"FOLLOWER","location":"http://172.151.57.131:9000/tablet?id=a0af6e0c05d54f42a3580b9b9b255fc3"}]}]:"Tasks",[]}

Table lineitem with oid 16450 and uuid 00004100000030008000000000004042 exists in yb1 but master leader API returns wrong table details - {"table_name":"yb1.lineitem","table_id":"00004100000030008000000000004042","table_version":9,"table_type":"PGSQL_TABLE_TYPE","table_state":"Running","table_state_message":"Current schema version=9","table_replication_info":{"live_replicas":{"num_replicas":3,"placement_blocks":[{"cloud_info":{"placement_cloud":"aws","placement_region":"us-west-2","placement_zone":"us-west-2a"},"min_num_replicas":1},{"cloud_info":{"placement_cloud":"aws","placement_region":"us-west-2","placement_zone":"us-west-2b"},"min_num_replicas":1},{"cloud_info":{"placement_cloud":"aws","placement_region":"us-west-2","placement_zone":"us-west-2c"},"min_num_replicas":1}],"placement_uuid":"d49113b5-a059-4778-9a13-f51b9b70beb9"},"affinitized_leaders":[{"placement_cloud":"aws","placement_region":"us-west-2","placement_zone":"us-west-2a"},{"placement_cloud":"aws","placement_region":"us-west-2","placement_zone":"us-west-2b"},{"placement_cloud":"aws","placement_region":"us-west-2","placement_zone":"us-west-2c"}]},"table_transaction_verifier_state":"cccd9547-f6df-4e41-9fd3-083dc30b1e4d","table_transaction_ddl":" Alter ","table_transaction_ddl_previous_table_name":"lineitem","table_transaction_ddl_previous_table_previous_schema":{"columns":[{"id":0,"name":"l_orderkey","type":{"main":"INT32"},"is_key":true,"is_nullable":false,"is_static":false,"is_counter":false,"sorting_type":2,"order":1,"pg_type_oid":23,"marked_for_deletion":false},{"id":1,"name":"l_linenumber","type":{"main":"INT32"},"is_key":true,"is_nullable":false,"is_static":false,"is_counter":false,"sorting_type":2,"order":4,"pg_type_oid":23,"marked_for_deletion":false},{"id":2,"name":"l_regionkey","type":{"main":"INT32"},"is_key":true,"is_nullable":false,"is_static":false,"is_counter":false,"sorting_type":2,"order":17,"pg_type_oid":23,"marked_for_deletion":false},{"id":3,"name":"l_partkey","type":{"main":"INT32"},"is_key":false,"is_nullable":true,"is_static":false,"is_counter":false,"sorting_type":0,"order":2,"pg_type_oid":23,"marked_for_deletion":false},{"id":4,"name":"l_suppkey","type":{"main":"INT32"},"is_key":false,"is_nullable":true,"is_static":false,"is_counter":false,"sorting_type":0,"order":3,"pg_type_oid":23,"marked_for_deletion":false},{"id":5,"name":"l_quantity","type":{"main":"DECIMAL"},"is_key":false,"is_nullable":true,"is_static":false,"is_counter":false,"sorting_type":0,"order":5,"pg_type_oid":1700,"marked_for_deletion":false},{"id":6,"name":"l_extendedprice","type":{"main":"DECIMAL"},"is_key":false,"is_nullable":true,"is_static":false,"is_counter":false,"sorting_type":0,"order":6,"pg_type_oid":1700,"marked_for_deletion":false},{"id":7,"name":"l_discount","type":{"main":"DECIMAL"},"is_key":false,"is_nullable":true,"is_static":false,"is_counter":false,"sorting_type":0,"order":7,"pg_type_oid":1700,"marked_for_deletion":false},{"id":8,"name":"l_tax","type":{"main":"DECIMAL"},"is_key":false,"is_nullable":true,"is_static":false,"is_counter":false,"sorting_type":0,"order":8,"pg_type_oid":1700,"marked_for_deletion":false},{"id":9,"name":"l_returnflag","type":{"main":"STRING"},"is_key":false,"is_nullable":true,"is_static":false,"is_counter":false,"sorting_type":0,"order":9,"pg_type_oid":1042,"marked_for_deletion":false},{"id":10,"name":"l_linestatus","type":{"main":"STRING"},"is_key":false,"is_nullable":true,"is_static":false,"is_counter":false,"sorting_type":0,"order":10,"pg_type_oid":1042,"marked_for_deletion":false},{"id":11,"name":"l_shipdate","type":{"main":"INT32"},"is_key":false,"is_nullable":true,"is_static":false,"is_counter":false,"sorting_type":0,"order":11,"pg_type_oid":1082,"marked_for_deletion":false},{"id":12,"name":"l_commitdate","type":{"main":"INT32"},"is_key":false,"is_nullable":true,"is_static":false,"is_counter":false,"sorting_type":0,"order":12,"pg_type_oid":1082,"marked_for_deletion":false},{"id":13,"name":"l_receiptdate","type":{"main":"INT32"},"is_key":false,"is_nullable":true,"is_static":false,"is_counter":false,"sorting_type":0,"order":13,"pg_type_oid":1082,"marked_for_deletion":false},{"id":14,"name":"l_shipinstruct","type":{"main":"STRING"},"is_key":false,"is_nullable":true,"is_static":false,"is_counter":false,"sorting_type":0,"order":14,"pg_type_oid":1042,"marked_for_deletion":false},{"id":15,"name":"l_shipmode","type":{"main":"STRING"},"is_key":false,"is_nullable":true,"is_static":false,"is_counter":false,"sorting_type":0,"order":15,"pg_type_oid":1042,"marked_for_deletion":false},{"id":16,"name":"l_comment","type":{"main":"STRING"},"is_key":false,"is_nullable":true,"is_static":false,"is_counter":false,"sorting_type":0,"order":16,"pg_type_oid":1043,"marked_for_deletion":false}],"table_properties":{"contain_counters":false,"is_transactional":true,"consistency_level":"STRONG","use_mangled_column_name":false,"is_ysql_catalog_table":false,"retain_delete_markers":false,"partitioning_version":1,"ysql_replica_identity":"CHANGE"},"colocated_table_id":{"colocation_id":1458871935},"DEPRECATED_pgschema_name":"public"},"table_transaction_ddl_previous_table_current_schema":"columns",[{"column":"l_orderkey","id":"0","type":"int32 NOT NULL RANGE_DESC_NULL_FIRST"},{"column":"l_linenumber","id":"1","type":"int32 NOT NULL RANGE_DESC_NULL_FIRST"},{"column":"l_regionkey","id":"2","type":"int32 NOT NULL RANGE_DESC_NULL_FIRST"},{"column":"l_partkey","id":"3","type":"int32 NULLABLE VALUE"},{"column":"l_suppkey","id":"4","type":"int32 NULLABLE VALUE"},{"column":"l_quantity","id":"5","type":"decimal NULLABLE VALUE"},{"column":"l_extendedprice","id":"6","type":"decimal NULLABLE VALUE"},{"column":"l_discount","id":"7","type":"decimal NULLABLE VALUE"},{"column":"l_tax","id":"8","type":"decimal NULLABLE VALUE"},{"column":"l_returnflag","id":"9","type":"string NULLABLE VALUE"},{"column":"l_linestatus","id":"10","type":"string NULLABLE VALUE"},{"column":"l_shipdate","id":"11","type":"int32 NULLABLE VALUE"},{"column":"l_commitdate","id":"12","type":"int32 NULLABLE VALUE"},{"column":"l_receiptdate","id":"13","type":"int32 NULLABLE VALUE"},{"column":"l_shipinstruct","id":"14","type":"string NULLABLE VALUE"},{"column":"l_shipmode","id":"15","type":"string NULLABLE VALUE"},{"column":"l_comment","id":"16","type":"string NULLABLE VALUE"}]:"tablets",[{"tablet_id":"a0af6e0c05d54f42a3580b9b9b255fc3","partition":"range: [&lt;start&gt;, &lt;end&gt;)","split_depth":0,"state":"Running","hidden":"false","message":"Tablet reported with an active leader","locations":[{"uuid":"6a397d935f694cd6aeb4e3b9c530ab72","role":"FOLLOWER","location":"http://172.151.28.142:9000/tablet?id=a0af6e0c05d54f42a3580b9b9b255fc3"},{"uuid":"a1f057437c314e669b73c41e9e326a59","role":"LEADER","location":"http://172.151.37.176:9000/tablet?id=a0af6e0c05d54f42a3580b9b9b255fc3"},{"uuid":"b15bbdee27b7436aa117cc780169e62f","role":"FOLLOWER","location":"http://172.151.57.131:9000/tablet?id=a0af6e0c05d54f42a3580b9b9b255fc3"}]}]:"Tasks",["task_type","TableSchemaVerificationTask","task_state","kRunning","task_time_since_started","19.3 s","task_running_secs","19.3 s","task_description","TableSchemaVerificationTask for lineitem [id=00004100000030008000000000004042]"]}
Table lineitem_1a with oid 16455 and uuid 00004100000030008000000000004047 exists in yb1 but master leader API returns wrong table details - {"table_name":"yb1.lineitem_1a","table_id":"00004100000030008000000000004047","table_version":10,"table_type":"PGSQL_TABLE_TYPE","table_state":"Running","table_state_message":"Current schema version=10","table_replication_info":{"live_replicas":{"num_replicas":3,"placement_blocks":[{"cloud_info":{"placement_cloud":"aws","placement_region":"us-west-2","placement_zone":"us-west-2a"},"min_num_replicas":1},{"cloud_info":{"placement_cloud":"aws","placement_region":"us-west-2","placement_zone":"us-west-2b"},"min_num_replicas":1},{"cloud_info":{"placement_cloud":"aws","placement_region":"us-west-2","placement_zone":"us-west-2c"},"min_num_replicas":1}],"placement_uuid":"d49113b5-a059-4778-9a13-f51b9b70beb9"},"affinitized_leaders":[{"placement_cloud":"aws","placement_region":"us-west-2","placement_zone":"us-west-2a"},{"placement_cloud":"aws","placement_region":"us-west-2","placement_zone":"us-west-2b"},{"placement_cloud":"aws","placement_region":"us-west-2","placement_zone":"us-west-2c"}]},"table_transaction_verifier_state":"cccd9547-f6df-4e41-9fd3-083dc30b1e4d","table_transaction_ddl":" Alter ","table_transaction_ddl_previous_table_name":"lineitem_1a","table_transaction_ddl_previous_table_previous_schema":{"columns":[{"id":0,"name":"l_orderkey","type":{"main":"INT32"},"is_key":true,"is_nullable":false,"is_static":false,"is_counter":false,"sorting_type":2,"order":1,"pg_type_oid":23,"marked_for_deletion":false},{"id":1,"name":"l_linenumber","type":{"main":"INT32"},"is_key":true,"is_nullable":false,"is_static":false,"is_counter":false,"sorting_type":2,"order":4,"pg_type_oid":23,"marked_for_deletion":false},{"id":2,"name":"l_regionkey","type":{"main":"INT32"},"is_key":true,"is_nullable":false,"is_static":false,"is_counter":false,"sorting_type":2,"order":17,"pg_type_oid":23,"marked_for_deletion":false},{"id":3,"name":"l_partkey","type":{"main":"INT32"},"is_key":false,"is_nullable":true,"is_static":false,"is_counter":false,"sorting_type":0,"order":2,"pg_type_oid":23,"marked_for_deletion":false},{"id":4,"name":"l_suppkey","type":{"main":"INT32"},"is_key":false,"is_nullable":true,"is_static":false,"is_counter":false,"sorting_type":0,"order":3,"pg_type_oid":23,"marked_for_deletion":false},{"id":5,"name":"l_quantity","type":{"main":"DECIMAL"},"is_key":false,"is_nullable":true,"is_static":false,"is_counter":false,"sorting_type":0,"order":5,"pg_type_oid":1700,"marked_for_deletion":false},{"id":6,"name":"l_extendedprice","type":{"main":"DECIMAL"},"is_key":false,"is_nullable":true,"is_static":false,"is_counter":false,"sorting_type":0,"order":6,"pg_type_oid":1700,"marked_for_deletion":false},{"id":7,"name":"l_discount","type":{"main":"DECIMAL"},"is_key":false,"is_nullable":true,"is_static":false,"is_counter":false,"sorting_type":0,"order":7,"pg_type_oid":1700,"marked_for_deletion":false},{"id":8,"name":"l_tax","type":{"main":"DECIMAL"},"is_key":false,"is_nullable":true,"is_static":false,"is_counter":false,"sorting_type":0,"order":8,"pg_type_oid":1700,"marked_for_deletion":false},{"id":9,"name":"l_returnflag","type":{"main":"STRING"},"is_key":false,"is_nullable":true,"is_static":false,"is_counter":false,"sorting_type":0,"order":9,"pg_type_oid":1042,"marked_for_deletion":false},{"id":10,"name":"l_linestatus","type":{"main":"STRING"},"is_key":false,"is_nullable":true,"is_static":false,"is_counter":false,"sorting_type":0,"order":10,"pg_type_oid":1042,"marked_for_deletion":false},{"id":11,"name":"l_shipdate","type":{"main":"INT32"},"is_key":false,"is_nullable":true,"is_static":false,"is_counter":false,"sorting_type":0,"order":11,"pg_type_oid":1082,"marked_for_deletion":false},{"id":12,"name":"l_commitdate","type":{"main":"INT32"},"is_key":false,"is_nullable":true,"is_static":false,"is_counter":false,"sorting_type":0,"order":12,"pg_type_oid":1082,"marked_for_deletion":false},{"id":13,"name":"l_receiptdate","type":{"main":"INT32"},"is_key":false,"is_nullable":true,"is_static":false,"is_counter":false,"sorting_type":0,"order":13,"pg_type_oid":1082,"marked_for_deletion":false},{"id":14,"name":"l_shipinstruct","type":{"main":"STRING"},"is_key":false,"is_nullable":true,"is_static":false,"is_counter":false,"sorting_type":0,"order":14,"pg_type_oid":1042,"marked_for_deletion":false},{"id":15,"name":"l_shipmode","type":{"main":"STRING"},"is_key":false,"is_nullable":true,"is_static":false,"is_counter":false,"sorting_type":0,"order":15,"pg_type_oid":1042,"marked_for_deletion":false},{"id":16,"name":"l_comment","type":{"main":"STRING"},"is_key":false,"is_nullable":true,"is_static":false,"is_counter":false,"sorting_type":0,"order":16,"pg_type_oid":1043,"marked_for_deletion":false}],"table_properties":{"contain_counters":false,"is_transactional":true,"consistency_level":"STRONG","use_mangled_column_name":false,"is_ysql_catalog_table":false,"retain_delete_markers":false,"partitioning_version":1,"ysql_replica_identity":"CHANGE"},"colocated_table_id":{"colocation_id":4254232115},"DEPRECATED_pgschema_name":"public"},"table_transaction_ddl_previous_table_current_schema":"columns",[{"column":"l_orderkey","id":"0","type":"int32 NOT NULL RANGE_DESC_NULL_FIRST"},{"column":"l_linenumber","id":"1","type":"int32 NOT NULL RANGE_DESC_NULL_FIRST"},{"column":"l_regionkey","id":"2","type":"int32 NOT NULL RANGE_DESC_NULL_FIRST"},{"column":"l_partkey","id":"3","type":"int32 NULLABLE VALUE"},{"column":"l_suppkey","id":"4","type":"int32 NULLABLE VALUE"},{"column":"l_quantity","id":"5","type":"decimal NULLABLE VALUE"},{"column":"l_extendedprice","id":"6","type":"decimal NULLABLE VALUE"},{"column":"l_discount","id":"7","type":"decimal NULLABLE VALUE"},{"column":"l_tax","id":"8","type":"decimal NULLABLE VALUE"},{"column":"l_returnflag","id":"9","type":"string NULLABLE VALUE"},{"column":"l_linestatus","id":"10","type":"string NULLABLE VALUE"},{"column":"l_shipdate","id":"11","type":"int32 NULLABLE VALUE"},{"column":"l_commitdate","id":"12","type":"int32 NULLABLE VALUE"},{"column":"l_receiptdate","id":"13","type":"int32 NULLABLE VALUE"},{"column":"l_shipinstruct","id":"14","type":"string NULLABLE VALUE"},{"column":"l_shipmode","id":"15","type":"string NULLABLE VALUE"},{"column":"l_comment","id":"16","type":"string NULLABLE VALUE"}]:"tablets",[{"tablet_id":"a0af6e0c05d54f42a3580b9b9b255fc3","partition":"range: [&lt;start&gt;, &lt;end&gt;)","split_depth":0,"state":"Running","hidden":"false","message":"Tablet reported with an active leader","locations":[{"uuid":"6a397d935f694cd6aeb4e3b9c530ab72","role":"FOLLOWER","location":"http://172.151.28.142:9000/tablet?id=a0af6e0c05d54f42a3580b9b9b255fc3"},{"uuid":"a1f057437c314e669b73c41e9e326a59","role":"LEADER","location":"http://172.151.37.176:9000/tablet?id=a0af6e0c05d54f42a3580b9b9b255fc3"},{"uuid":"b15bbdee27b7436aa117cc780169e62f","role":"FOLLOWER","location":"http://172.151.57.131:9000/tablet?id=a0af6e0c05d54f42a3580b9b9b255fc3"}]}]:"Tasks",[]}
Table lineitem_1b with oid 16460 and uuid 0000410000003000800000000000404c exists in yb1 but master leader API returns wrong table details - {"table_name":"yb1.lineitem_1b","table_id":"0000410000003000800000000000404c","table_version":10,"table_type":"PGSQL_TABLE_TYPE","table_state":"Running","table_state_message":"Current schema version=10","table_replication_info":{"live_replicas":{"num_replicas":3,"placement_blocks":[{"cloud_info":{"placement_cloud":"aws","placement_region":"us-west-2","placement_zone":"us-west-2a"},"min_num_replicas":1},{"cloud_info":{"placement_cloud":"aws","placement_region":"us-west-2","placement_zone":"us-west-2b"},"min_num_replicas":1},{"cloud_info":{"placement_cloud":"aws","placement_region":"us-west-2","placement_zone":"us-west-2c"},"min_num_replicas":1}],"placement_uuid":"d49113b5-a059-4778-9a13-f51b9b70beb9"},"affinitized_leaders":[{"placement_cloud":"aws","placement_region":"us-west-2","placement_zone":"us-west-2a"},{"placement_cloud":"aws","placement_region":"us-west-2","placement_zone":"us-west-2b"},{"placement_cloud":"aws","placement_region":"us-west-2","placement_zone":"us-west-2c"}]},"table_transaction_verifier_state":"cccd9547-f6df-4e41-9fd3-083dc30b1e4d","table_transaction_ddl":" Alter ","table_transaction_ddl_previous_table_name":"lineitem_1b","table_transaction_ddl_previous_table_previous_schema":{"columns":[{"id":0,"name":"l_orderkey","type":{"main":"INT32"},"is_key":true,"is_nullable":false,"is_static":false,"is_counter":false,"sorting_type":2,"order":1,"pg_type_oid":23,"marked_for_deletion":false},{"id":1,"name":"l_linenumber","type":{"main":"INT32"},"is_key":true,"is_nullable":false,"is_static":false,"is_counter":false,"sorting_type":2,"order":4,"pg_type_oid":23,"marked_for_deletion":false},{"id":2,"name":"l_regionkey","type":{"main":"INT32"},"is_key":true,"is_nullable":false,"is_static":false,"is_counter":false,"sorting_type":2,"order":17,"pg_type_oid":23,"marked_for_deletion":false},{"id":3,"name":"l_partkey","type":{"main":"INT32"},"is_key":false,"is_nullable":true,"is_static":false,"is_counter":false,"sorting_type":0,"order":2,"pg_type_oid":23,"marked_for_deletion":false},{"id":4,"name":"l_suppkey","type":{"main":"INT32"},"is_key":false,"is_nullable":true,"is_static":false,"is_counter":false,"sorting_type":0,"order":3,"pg_type_oid":23,"marked_for_deletion":false},{"id":5,"name":"l_quantity","type":{"main":"DECIMAL"},"is_key":false,"is_nullable":true,"is_static":false,"is_counter":false,"sorting_type":0,"order":5,"pg_type_oid":1700,"marked_for_deletion":false},{"id":6,"name":"l_extendedprice","type":{"main":"DECIMAL"},"is_key":false,"is_nullable":true,"is_static":false,"is_counter":false,"sorting_type":0,"order":6,"pg_type_oid":1700,"marked_for_deletion":false},{"id":7,"name":"l_discount","type":{"main":"DECIMAL"},"is_key":false,"is_nullable":true,"is_static":false,"is_counter":false,"sorting_type":0,"order":7,"pg_type_oid":1700,"marked_for_deletion":false},{"id":8,"name":"l_tax","type":{"main":"DECIMAL"},"is_key":false,"is_nullable":true,"is_static":false,"is_counter":false,"sorting_type":0,"order":8,"pg_type_oid":1700,"marked_for_deletion":false},{"id":9,"name":"l_returnflag","type":{"main":"STRING"},"is_key":false,"is_nullable":true,"is_static":false,"is_counter":false,"sorting_type":0,"order":9,"pg_type_oid":1042,"marked_for_deletion":false},{"id":10,"name":"l_linestatus","type":{"main":"STRING"},"is_key":false,"is_nullable":true,"is_static":false,"is_counter":false,"sorting_type":0,"order":10,"pg_type_oid":1042,"marked_for_deletion":false},{"id":11,"name":"l_shipdate","type":{"main":"INT32"},"is_key":false,"is_nullable":true,"is_static":false,"is_counter":false,"sorting_type":0,"order":11,"pg_type_oid":1082,"marked_for_deletion":false},{"id":12,"name":"l_commitdate","type":{"main":"INT32"},"is_key":false,"is_nullable":true,"is_static":false,"is_counter":false,"sorting_type":0,"order":12,"pg_type_oid":1082,"marked_for_deletion":false},{"id":13,"name":"l_receiptdate","type":{"main":"INT32"},"is_key":false,"is_nullable":true,"is_static":false,"is_counter":false,"sorting_type":0,"order":13,"pg_type_oid":1082,"marked_for_deletion":false},{"id":14,"name":"l_shipinstruct","type":{"main":"STRING"},"is_key":false,"is_nullable":true,"is_static":false,"is_counter":false,"sorting_type":0,"order":14,"pg_type_oid":1042,"marked_for_deletion":false},{"id":15,"name":"l_shipmode","type":{"main":"STRING"},"is_key":false,"is_nullable":true,"is_static":false,"is_counter":false,"sorting_type":0,"order":15,"pg_type_oid":1042,"marked_for_deletion":false},{"id":16,"name":"l_comment","type":{"main":"STRING"},"is_key":false,"is_nullable":true,"is_static":false,"is_counter":false,"sorting_type":0,"order":16,"pg_type_oid":1043,"marked_for_deletion":false}],"table_properties":{"contain_counters":false,"is_transactional":true,"consistency_level":"STRONG","use_mangled_column_name":false,"is_ysql_catalog_table":false,"retain_delete_markers":false,"partitioning_version":1,"ysql_replica_identity":"CHANGE"},"colocated_table_id":{"colocation_id":109259261},"DEPRECATED_pgschema_name":"public"},"table_transaction_ddl_previous_table_current_schema":"columns",[{"column":"l_orderkey","id":"0","type":"int32 NOT NULL RANGE_DESC_NULL_FIRST"},{"column":"l_linenumber","id":"1","type":"int32 NOT NULL RANGE_DESC_NULL_FIRST"},{"column":"l_regionkey","id":"2","type":"int32 NOT NULL RANGE_DESC_NULL_FIRST"},{"column":"l_partkey","id":"3","type":"int32 NULLABLE VALUE"},{"column":"l_suppkey","id":"4","type":"int32 NULLABLE VALUE"},{"column":"l_quantity","id":"5","type":"decimal NULLABLE VALUE"},{"column":"l_extendedprice","id":"6","type":"decimal NULLABLE VALUE"},{"column":"l_discount","id":"7","type":"decimal NULLABLE VALUE"},{"column":"l_tax","id":"8","type":"decimal NULLABLE VALUE"},{"column":"l_returnflag","id":"9","type":"string NULLABLE VALUE"},{"column":"l_linestatus","id":"10","type":"string NULLABLE VALUE"},{"column":"l_shipdate","id":"11","type":"int32 NULLABLE VALUE"},{"column":"l_commitdate","id":"12","type":"int32 NULLABLE VALUE"},{"column":"l_receiptdate","id":"13","type":"int32 NULLABLE VALUE"},{"column":"l_shipinstruct","id":"14","type":"string NULLABLE VALUE"},{"column":"l_shipmode","id":"15","type":"string NULLABLE VALUE"},{"column":"l_comment","id":"16","type":"string NULLABLE VALUE"}]:"tablets",[{"tablet_id":"a0af6e0c05d54f42a3580b9b9b255fc3","partition":"range: [&lt;start&gt;, &lt;end&gt;)","split_depth":0,"state":"Running","hidden":"false","message":"Tablet reported with an active leader","locations":[{"uuid":"6a397d935f694cd6aeb4e3b9c530ab72","role":"FOLLOWER","location":"http://172.151.28.142:9000/tablet?id=a0af6e0c05d54f42a3580b9b9b255fc3"},{"uuid":"a1f057437c314e669b73c41e9e326a59","role":"LEADER","location":"http://172.151.37.176:9000/tablet?id=a0af6e0c05d54f42a3580b9b9b255fc3"},{"uuid":"b15bbdee27b7436aa117cc780169e62f","role":"FOLLOWER","location":"http://172.151.57.131:9000/tablet?id=a0af6e0c05d54f42a3580b9b9b255fc3"}]}]:"Tasks",[]}
Table lineitem_1c with oid 16465 and uuid 00004100000030008000000000004051 exists in yb1 but master leader API returns wrong table details - {"table_name":"yb1.lineitem_1c","table_id":"00004100000030008000000000004051","table_version":10,"table_type":"PGSQL_TABLE_TYPE","table_state":"Running","table_state_message":"Current schema version=10","table_replication_info":{"live_replicas":{"num_replicas":3,"placement_blocks":[{"cloud_info":{"placement_cloud":"aws","placement_region":"us-west-2","placement_zone":"us-west-2a"},"min_num_replicas":1},{"cloud_info":{"placement_cloud":"aws","placement_region":"us-west-2","placement_zone":"us-west-2b"},"min_num_replicas":1},{"cloud_info":{"placement_cloud":"aws","placement_region":"us-west-2","placement_zone":"us-west-2c"},"min_num_replicas":1}],"placement_uuid":"d49113b5-a059-4778-9a13-f51b9b70beb9"},"affinitized_leaders":[{"placement_cloud":"aws","placement_region":"us-west-2","placement_zone":"us-west-2a"},{"placement_cloud":"aws","placement_region":"us-west-2","placement_zone":"us-west-2b"},{"placement_cloud":"aws","placement_region":"us-west-2","placement_zone":"us-west-2c"}]},"table_transaction_verifier_state":"cccd9547-f6df-4e41-9fd3-083dc30b1e4d","table_transaction_ddl":" Alter ","table_transaction_ddl_previous_table_name":"lineitem_1c","table_transaction_ddl_previous_table_previous_schema":{"columns":[{"id":0,"name":"l_orderkey","type":{"main":"INT32"},"is_key":true,"is_nullable":false,"is_static":false,"is_counter":false,"sorting_type":2,"order":1,"pg_type_oid":23,"marked_for_deletion":false},{"id":1,"name":"l_linenumber","type":{"main":"INT32"},"is_key":true,"is_nullable":false,"is_static":false,"is_counter":false,"sorting_type":2,"order":4,"pg_type_oid":23,"marked_for_deletion":false},{"id":2,"name":"l_regionkey","type":{"main":"INT32"},"is_key":true,"is_nullable":false,"is_static":false,"is_counter":false,"sorting_type":2,"order":17,"pg_type_oid":23,"marked_for_deletion":false},{"id":3,"name":"l_partkey","type":{"main":"INT32"},"is_key":false,"is_nullable":true,"is_static":false,"is_counter":false,"sorting_type":0,"order":2,"pg_type_oid":23,"marked_for_deletion":false},{"id":4,"name":"l_suppkey","type":{"main":"INT32"},"is_key":false,"is_nullable":true,"is_static":false,"is_counter":false,"sorting_type":0,"order":3,"pg_type_oid":23,"marked_for_deletion":false},{"id":5,"name":"l_quantity","type":{"main":"DECIMAL"},"is_key":false,"is_nullable":true,"is_static":false,"is_counter":false,"sorting_type":0,"order":5,"pg_type_oid":1700,"marked_for_deletion":false},{"id":6,"name":"l_extendedprice","type":{"main":"DECIMAL"},"is_key":false,"is_nullable":true,"is_static":false,"is_counter":false,"sorting_type":0,"order":6,"pg_type_oid":1700,"marked_for_deletion":false},{"id":7,"name":"l_discount","type":{"main":"DECIMAL"},"is_key":false,"is_nullable":true,"is_static":false,"is_counter":false,"sorting_type":0,"order":7,"pg_type_oid":1700,"marked_for_deletion":false},{"id":8,"name":"l_tax","type":{"main":"DECIMAL"},"is_key":false,"is_nullable":true,"is_static":false,"is_counter":false,"sorting_type":0,"order":8,"pg_type_oid":1700,"marked_for_deletion":false},{"id":9,"name":"l_returnflag","type":{"main":"STRING"},"is_key":false,"is_nullable":true,"is_static":false,"is_counter":false,"sorting_type":0,"order":9,"pg_type_oid":1042,"marked_for_deletion":false},{"id":10,"name":"l_linestatus","type":{"main":"STRING"},"is_key":false,"is_nullable":true,"is_static":false,"is_counter":false,"sorting_type":0,"order":10,"pg_type_oid":1042,"marked_for_deletion":false},{"id":11,"name":"l_shipdate","type":{"main":"INT32"},"is_key":false,"is_nullable":true,"is_static":false,"is_counter":false,"sorting_type":0,"order":11,"pg_type_oid":1082,"marked_for_deletion":false},{"id":12,"name":"l_commitdate","type":{"main":"INT32"},"is_key":false,"is_nullable":true,"is_static":false,"is_counter":false,"sorting_type":0,"order":12,"pg_type_oid":1082,"marked_for_deletion":false},{"id":13,"name":"l_receiptdate","type":{"main":"INT32"},"is_key":false,"is_nullable":true,"is_static":false,"is_counter":false,"sorting_type":0,"order":13,"pg_type_oid":1082,"marked_for_deletion":false},{"id":14,"name":"l_shipinstruct","type":{"main":"STRING"},"is_key":false,"is_nullable":true,"is_static":false,"is_counter":false,"sorting_type":0,"order":14,"pg_type_oid":1042,"marked_for_deletion":false},{"id":15,"name":"l_shipmode","type":{"main":"STRING"},"is_key":false,"is_nullable":true,"is_static":false,"is_counter":false,"sorting_type":0,"order":15,"pg_type_oid":1042,"marked_for_deletion":false},{"id":16,"name":"l_comment","type":{"main":"STRING"},"is_key":false,"is_nullable":true,"is_static":false,"is_counter":false,"sorting_type":0,"order":16,"pg_type_oid":1043,"marked_for_deletion":false}],"table_properties":{"contain_counters":false,"is_transactional":true,"consistency_level":"STRONG","use_mangled_column_name":false,"is_ysql_catalog_table":false,"retain_delete_markers":false,"partitioning_version":1,"ysql_replica_identity":"CHANGE"},"colocated_table_id":{"colocation_id":4222066058},"DEPRECATED_pgschema_name":"public"},"table_transaction_ddl_previous_table_current_schema":"columns",[{"column":"l_orderkey","id":"0","type":"int32 NOT NULL RANGE_DESC_NULL_FIRST"},{"column":"l_linenumber","id":"1","type":"int32 NOT NULL RANGE_DESC_NULL_FIRST"},{"column":"l_regionkey","id":"2","type":"int32 NOT NULL RANGE_DESC_NULL_FIRST"},{"column":"l_partkey","id":"3","type":"int32 NULLABLE VALUE"},{"column":"l_suppkey","id":"4","type":"int32 NULLABLE VALUE"},{"column":"l_quantity","id":"5","type":"decimal NULLABLE VALUE"},{"column":"l_extendedprice","id":"6","type":"decimal NULLABLE VALUE"},{"column":"l_discount","id":"7","type":"decimal NULLABLE VALUE"},{"column":"l_tax","id":"8","type":"decimal NULLABLE VALUE"},{"column":"l_returnflag","id":"9","type":"string NULLABLE VALUE"},{"column":"l_linestatus","id":"10","type":"string NULLABLE VALUE"},{"column":"l_shipdate","id":"11","type":"int32 NULLABLE VALUE"},{"column":"l_commitdate","id":"12","type":"int32 NULLABLE VALUE"},{"column":"l_receiptdate","id":"13","type":"int32 NULLABLE VALUE"},{"column":"l_shipinstruct","id":"14","type":"string NULLABLE VALUE"},{"column":"l_shipmode","id":"15","type":"string NULLABLE VALUE"},{"column":"l_comment","id":"16","type":"string NULLABLE VALUE"}]:"tablets",[{"tablet_id":"a0af6e0c05d54f42a3580b9b9b255fc3","partition":"range: [&lt;start&gt;, &lt;end&gt;)","split_depth":0,"state":"Running","hidden":"false","message":"Tablet reported with an active leader","locations":[{"uuid":"6a397d935f694cd6aeb4e3b9c530ab72","role":"FOLLOWER","location":"http://172.151.28.142:9000/tablet?id=a0af6e0c05d54f42a3580b9b9b255fc3"},{"uuid":"a1f057437c314e669b73c41e9e326a59","role":"LEADER","location":"http://172.151.37.176:9000/tablet?id=a0af6e0c05d54f42a3580b9b9b255fc3"},{"uuid":"b15bbdee27b7436aa117cc780169e62f","role":"FOLLOWER","location":"http://172.151.57.131:9000/tablet?id=a0af6e0c05d54f42a3580b9b9b255fc3"}]}]:"Tasks",[]}
* Debug
** https://stress.dev.yugabyte.com/stress_test/f8f4ae2a-77ba-4c26-964b-017853b73f3a
  Observations
*** tserver
- [[https://stress.dev.yugabyte.com/files/get?name=6e2385a1-a161-4010-890d-45ca5c565f31-yb-tserver.ip-172-151-30-10.us-west-2.compute.internal.yugabyte.log.WARNING.20250805-122000.97272][yb-tserver.ip-172-151-30-10]]
  Logs
  1. E0805 15:38:01.676355 258036 consensus_queue.cc:1889] Invalid peer UUID: 404bef6bf4444d968246afcc344daaea
  2. W0805 15:38:11.109555 258989 consensus_peers.cc:625] T 54e7ed8b9c5b4f869adc81b1fc784d0c P 057a7221d25a4ea48dfac73d079e8afd -> Peer 1cf512aa43f2420b8d698c425b6e6deb ([host: "172.151.20.109" port: 9100], []): Couldn't send request.  Status: Timed out (yb/rpc/outbound_call.cc:647): UpdateConsensus RPC (request call id 2475807) to 172.151.20.109:9100 timed out after 3.000s. Retrying in the next heartbeat period. Already tried 2 times. State: 2
-
  Logs
  #+begin_src shell
    I0805 15:18:03.068440 33633 update_txn_operation.cc:82] T 32d8520d4c054b6f8f33067d6a5d1008 0x0000318f11df9110 -> { type: kUpdateTransaction consensus_round: <NULL> ht: <invalid> }: Aborted: Service unavailable (yb/tablet/operations/operation_tracker.cc:190): Operation of type kUpdateTransaction failed: tablet 32d8520d4c054b6f8f33067d6a5d1008 hit the limit 3746056765 of memory tracker 0x0000318dffc02860 -> root while trying to consume an additional 26 bytes; the memory tracker had already given out 4375265280 bytes.

    I0805 15:18:03.068452 33635 update_txn_operation.cc:82] T fb9ee57e7c9e4866b3c84359d5604ef2 0x0000318f144dda00 -> { type: kUpdateTransaction consensus_round: <NULL> ht: <invalid> }: Aborted: Service unavailable (yb/tablet/operations/operation_tracker.cc:190): Operation of type kUpdateTransaction failed: tablet fb9ee57e7c9e4866b3c84359d5604ef2 hit the limit 3746056765 of memory tracker 0x0000318dffc02860 -> root while trying to consume an additional 26 bytes; the memory tracker had already given out 4375265280 bytes.
  #+end_src
*** Backup failed
- ysql dump failed
  #+begin_src java
    java.lang.RuntimeException: Task id 997c9345-9f15-4c19-82da-bbfc6f351e53_PGSQL_TABLE_TYPE_db1_357322ce-a0e8-43d4-8680-ce793279e182 status: Task failed during YSQL Dump phase with status CATALOG_VERSION_COMMAND_FAILED. Please check YB-Controller logs on node 172.151.20.109 for more details
        at com.yugabyte.yw.commissioner.YbcTaskBase.handleTaskCompleteStage(YbcTaskBase.java:129)
        at com.yugabyte.yw.commissioner.YbcTaskBase.pollTaskProgress(YbcTaskBase.java:66)
        at com.yugabyte.yw.commissioner.tasks.subtasks.BackupTableYbc.run(BackupTableYbc.java:208)
        at com.yugabyte.yw.commissioner.TaskExecutor$AbstractRunnableTask.run(TaskExecutor.java:1041)
        at com.yugabyte.yw.commissioner.TaskExecutor$RunnableSubTask.run(TaskExecutor.java:1551)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
        at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
        at com.yugabyte.yw.common.logging.MDCAwareRunnable.run(MDCAwareRunnable.java:46)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.base/java.lang.Thread.run(Unknown Source)
  #+end_src
*** master
- Logs
  1. [[https://stress.dev.yugabyte.com/files/get?name=d18518f5-6e0f-49a0-91ef-84cdae3b6911-yb-master.ip-172-151-20-109.us-west-2.compute.internal.yugabyte.log.WARNING.20250805-110239.32245][yb-master.ip-172-151-20-109]]
  #+begin_src shell
    W0805 15:18:00.405433 236846 catalog_manager.cc:11918] Expected replicas 3 but found 2 for tablet d4f00c2631254adea06840145d2cb3e4: tablet_id: "d4f00c2631254adea06840145d2cb3e4" replicas { ts_info { permanent_uuid: "057a7221d25a4ea48dfac73d079e8afd" private_rpc_addresses { host: "172.151.30.10" port: 9100 } cloud_info { placement_cloud: "aws" placement_region: "us-west-2" placement_zone: "us-west-2a" } placement_uuid: "141db162-b5cc-49c1-a64a-4a220a69f211" } role: LEADER member_type: VOTER state: RUNNING } replicas { ts_info { permanent_uuid: "1cf512aa43f2420b8d698c425b6e6deb" private_rpc_addresses { host: "172.151.20.109" port: 9100 } cloud_info { placement_cloud: "aws" placement_region: "us-west-2" placement_zone: "us-west-2a" } placement_uuid: "141db162-b5cc-49c1-a64a-4a220a69f211" } role: FOLLOWER member_type: VOTER state: RUNNING } stale: false partition { partition_key_start: "0\000" partition_key_end: "@\000" } table_id: "000034cb000030008000000000004101" table_ids: "000034cb000030008000000000004201" table_ids: "000034cb000030008000000000004101" split_depth: 0 expected_live_replicas: 3 expected_read_replicas: 0 split_parent_tablet_id: "" raft_config_opid_index: 17613 [suppressed 1 similar messages]
  #+end_src
** test_bank_workloads_with_pq https://stress.dev.yugabyte.com/stress_test/be65df77-d7ea-480e-97e5-82494f164089
** [[https://stress.dev.yugabyte.com/stress_test/6d3593a0-2356-4d01-8b00-37d255f3313d][test_rbs_long_running_regress]] remove node failed
** [[https://stress.dev.yugabyte.com/stress_test/6daaa106-c0dc-4419-a9df-ee1f650e8769][test_cross_db_concurrent_ddls]] connection mgr test - batch inserts failed
- [[https://stress.dev.yugabyte.com/stress_test/31289f09-73a5-4a5e-bb96-ac48eb9d4c3b][test_cross_db_concurrent_ddls]]
- [[https://stress.dev.yugabyte.com/stress_test/232d2793-09d9-4bee-bd46-e6d381a1047d][test_cross_db_concurrent_ddls]]
- [[https://stress.dev.yugabyte.com/stress_test/9286874d-d422-45b3-8a8e-3dd6ef800a5f][test_cross_db_concurrent_ddls]]
** No results were returned by the query
- [[https://stress.dev.yugabyte.com/stress_test/c8794257-128e-4c8f-b4b3-1d448f0e1312][test_cross_db_concurrent_ddls]]
** [[https://stress.dev.yugabyte.com/stress_test/5d6d9682-5563-48d0-840e-501763e85f75][test_rbs_long_running_regress]]
1. Rolling restart failed due to under-replication
2. master tablet 0 is under-replictaed
3. master hosts 172.151.28.165(m1) and 172.151.18.219(m2)
   - m2 is restarted at around 04:48:26
   - m2 become pre-voter at around 04:48:48
   - I0901 04:48:46.397696  9195 raft_consensus.cc:1070] T 00000000000000000000000000000000 P 827da5bcb2554d75a0fa475a0b2594a5 [term 3 FOLLOWER]: ReportFailDetected: Starting NORMAL_ELECTION...
     I0901 04:48:46.684111  9196 generic_service.cc:73] 172.151.27.53:47272 changing flag via RPC: master_addresses
     W0901 04:48:46.684150  9196 flags.cc:883] Forcing change of non-runtime-safe flag master_addresses
     I0901 04:48:46.684170  9196 flags.cc:914] Changed flag 'master_addresses' from '' to '172.151.28.165:7100,172.161.18.219:7100,172.151.34.163:7100,172.151.50.36:7100'
     I0901 04:48:46.731384  8961 secure_stream.cc:878] SECURE[S] kEnabled { local: 172.161.18.219:7100 remote: 172.151.27.53:47272 }: Network error (yb/rpc/secure_stream.cc:877): SSL read failed: no error (6)
     I0901 04:48:48.071038  9196 generic_service.cc:73] 172.151.27.53:47304 changing flag via RPC: master_addresses
     W0901 04:48:48.071081  9196 flags.cc:883] Forcing change of non-runtime-safe flag master_addresses
     I0901 04:48:48.071100  9196 flags.cc:914] Changed flag 'master_addresses' from '172.151.28.165:7100,172.161.18.219:7100,172.151.34.163:7100,172.151.50.36:7100' to '172.151.28.165:7100,172.161.18.219:7100,172.151.34.163:7100'
     I0901 04:48:48.117285  8961 secure_stream.cc:878] SECURE[S] kEnabled { local: 172.161.18.219:7100 remote: 172.151.27.53:47304 }: Network error (yb/rpc/secure_stream.cc:877): SSL read failed: no error (6)
     W0901 04:48:49.754460  9197 yb_rpc.cc:376] Call yb.consensus.ConsensusService.UpdateConsensus 172.151.28.165:37699 => 172.161.18.219:7100 (request call id 1035620) took 3002ms (client timeout 3000ms).

Logs from m1
1. W0901 04:48:45.856549 198111 catalog_manager.cc:12152] Expected replicas 6 but found 7 for tablet 252b6c47c8df42a49189ccfb17ea5635
2. I0901 04:48:47.304049 205563 raft_consensus.cc:2580] Received ChangeConfig request tablet_id: "00000000000000000000000000000000" type: REMOVE_SERVER server { permanent_uuid: "c79b0ad230fb4b2181f51a4bfcdd61c6" last_known_private_addr { host: "172.151.50.36" port: 7100 } }

unresolved
1. why there are 4 masters ?
   - one the maser at 172.151.50.136 is being removed
2. why m1 is under-replicated ?
   - m1 is being removed and is in process
* D45476
1. [[https://stress.dev.yugabyte.com/stress_test/c9f966b9-c148-463b-87a1-d885b1fbccc1][test_ysql_bank_operations_rc]] core dump
2. [[https://stress.dev.yugabyte.com/stress_test/f2aa87b8-ff2e-40ef-b9e6-1e7369f1520d][test_parallel_query]] correctness issue
3. test_rbs_long_running_regress - re-running, failed to create universe
4. [[https://stress.dev.yugabyte.com/stress_test/5bd3b0dc-af11-4026-a0bb-59a565ae244f][test_backward_scan_with_parallel_query]] - correctness issue
   1. One known segv fault: https://github.com/yugabyte/yugabyte-db/issues/27954
5. [[https://stress.dev.yugabyte.com/stress_test/b3927cd1-4323-4aea-923b-13c5dbcebd2f][test_pgvector]] - re-run and check error
* <2025-09-08 Mon 12:27> dev unit test for langauge features
- some unit test template
- import postgres unit tests
- use ai for covering langauge layer features
* <2025-09-22 Mon 10:33>
** Core dump with ABRT signal
*** [[https://stress.dev.yugabyte.com/stress_test/818f8c09-1618-4586-b40f-9e82723804a9][test_ysql_bank_operations_rc]]
- slack: https://yugabyte.slack.com/archives/C027M2T0W8Z/p1756154760016829
- seems already fixed
*** [[https://stress.dev.yugabyte.com/stress_test/bd991109-1349-4601-977d-d0c88165844e][test_pgvector]]
- stuck rpc calls
